version: "2"
run:
  modules-download-mode: readonly
  issues-exit-code: 1
linters:
  default: none
  enable:
    - errcheck
    - errorlint
    - godox
    - govet
    - ineffassign
    - misspell
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unused
  settings:
    revive:
      enable-all-rules: false
      rules:
        - name: bare-return
        - name: call-to-gc
        - name: confusing-results
        - name: constant-logical-expr
        - name: context-as-argument
        - name: deep-exit
        - name: defer
        - name: duplicated-imports
        - name: early-return
        - name: empty-block
        - name: error-strings
        - name: errorf
        - name: exported
          arguments:
            - checkPrivateReceivers
        - name: imports-blocklist
          arguments:
            - github.com/pkg/errors
        - name: increment-decrement
        - name: range
        - name: range-val-address
        - name: range-val-in-closure
        - name: receiver-naming
        - name: struct-tag
        - name: time-naming
        - name: unconditional-recursion
        - name: unexported-naming
        - name: unexported-return
        - name: unnecessary-stmt
        - name: unreachable-code
        - name: unused-parameter
        - name: unused-receiver
        - name: var-declaration
        - name: waitgroup-by-value
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/andrewkroh/gvm
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
